## Session 1
 

In [8]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([3, 5, 7, 9, 11])

In [3]:
y_pred_1 = 2 * x + 1
y_pred_2 = 1.5 * x + 2


In [4]:
print(y_pred_1)
print(y_pred_2)

[ 3  5  7  9 11]
[3.5 5.  6.5 8.  9.5]


In [5]:
mae_f1 = np.mean(np.abs(y - y_pred_1))
mae_f2 = np.mean(np.abs(y - y_pred_2))

print("MAE for f1 =", mae_f1)
print("MAE for f2 =", mae_f2)

mse_1 = np.mean((y - y_pred_1) ** 2)
mse_2 = np.mean((y - y_pred_2) ** 2)

print("MSE of f1:", mse_1)
print("MSE of f2:", mse_2)

MAE for f1 = 0.0
MAE for f2 = 0.7
MSE of f1: 0.0
MSE of f2: 0.75


In [6]:
x_new = 6

f1_prediction = 2 * x_new + 1
f2_prediction = 1.5 * x_new + 2

print("Prediction of f1 for x=6:", f1_prediction)
print("Prediction of f2 for x=6:", f2_prediction)

Prediction of f1 for x=6: 13
Prediction of f2 for x=6: 11.0


In [7]:
y = np.array([4, 6, 8, 10])
y_hat = np.array([5, 5, 9, 7])

errors = y_hat - y

mae = np.mean(np.abs(errors))
mse = np.mean(errors ** 2)
mbe = np.mean(errors)

print("Errors:", errors)
print("MAE:", mae)
print("MSE:", mse)
print("MBE:", mbe)

Errors: [ 1 -1  1 -3]
MAE: 1.5
MSE: 3.0
MBE: -0.5


## Session 2

In [11]:
import pandas as pd

In [10]:
url = "https://raw.githubusercontent.com/al102030/Introduction-to-the-Machine-Learning-and-Big-Data-Practice/main/student_pass_fail_dataset.csv"

df = pd.read_csv(url)
df.head()

,hours_studied,attendance,pass
0,5.618102,5.168172,0
1,14.260715,53.135463,1
2,10.979909,54.063512,1
3,8.979877,63.742990,0
4,2.340280,72.609133,0


In [6]:
import os
print(os.getcwd())
print(os.listdir())

/content
['.config', 'sample_data']


## Session 3

In [ ]:
#Common distance measures
    # Euclidean distance:
    # d(x, y) = sqrt( sumi (xi – yi)2 )
    # Squared Euclidean distance:
    # d_sq(x, y) = sumi (xi – yi)2
    # Manhattan distance:
    # d(x, y) = sumi |xi – yi|
    # Minkowski distance:
    # d(x, y) = ( sumi |xi – yi|p )1/p

In [ ]:
# Euclidean distance:
import numpy as np

x = np.array([10, 85])
y = np.array([6, 70])

distance = np.sqrt(np.sum((x - y) ** 2))

print(distance)

15.524174696260024


In [14]:
# Squared Euclidean distance:
import numpy as np

x = np.array([10, 85])
y = np.array([6, 70])

squared_distance = np.sum((x - y) ** 2)

print(squared_distance)

241


In [15]:
# Minkowski distance:
import numpy as np

x = np.array([10, 85])
y = np.array([6, 70])

manhattan_distance = np.sum(np.abs(x - y))

print(manhattan_distance)

19


In [3]:
# Task 1
import numpy as np

A = np.array([1, 1])
B = np.array([3, 2])
C = np.array([4, 6])
D = np.array([7, 5])

# Euclidean distance between A and B
d1 = np.sqrt(np.sum((A - B) ** 2))
print(d1)

# Manhattan distance between A and B
d2 = np.sum(np.abs(A - B))
print(d2)

2.23606797749979
3


In [ ]:
# Euclidean Distance Matrix:
#
#      A        B        C          D
# A    0        2.23     5.83       7.21
# B    2.23     0        4.12       5
# C    5.83     4.12     0          3.16
# D    7.21     5        3.16       0

In [ ]:
# Manhattan Distance Matrix:
#
#        A     B     C     D
# A      0     3     8     10
# B      3     0     5     7
# C      8     5     0     4
# D      10    7     4     0

In [5]:
# Task 2:
import numpy as np

A = np.array([1, 1])
B = np.array([3, 2])

In [ ]:
# d1(x,y) = |x - y|
def d1(x, y):
    return abs(x - y)

d1(A, B) == d1(B, A)

array([ True,  True])

In [13]:
# d2(x, y) = (x - y)^2
def d2(x, y):
    return np.sum((x - y) ** 2)

d2(A, B) == d2(B, A)

np.True_

In [ ]:
# d3(x,y) = 0 for all x,y
def d3(x, y):
    return 0

d3(A, B)

In [16]:
# d4(x, y) = |x-y| if x >= y, else 2|x-y
def d4(x, y):
    if np.all(x >= y):
        return abs(x - y)
    else:
        return 2 * abs(x - y)

d4(A, B)

array([4, 2])

In [24]:
#  Task 3:
import numpy as np

A = np.array([1.0, 1.0])
B = np.array([1.5, 2.0])
C = np.array([2.0, 1.2])
D = np.array([5.0, 5.0])
E = np.array([6.0, 5.5])
F = np.array([5.5, 6.5])

mu1 = np.array([1.0, 2.8])
mu2 = np.array([6.2, 4.5])

def squ_euc(x, mu):
    return np.sum((x - mu) ** 2)

points = {
    "A": A,
    "B": B,
    "C": C,
    "D": D,
    "E": E,
    "F": F
}

C1 = set()
C2 = set()
J_before = 0

for name, point in points.items():
    d_mu1 = squ_euc(point, mu1)
    d_mu2 = squ_euc(point, mu2)
    
    if d_mu1 < d_mu2:
        C1.add(name)
        J_before += d_mu1
    else:
        C2.add(name)
        J_before += d_mu2
    
print(C1, C2)

{'A', 'B', 'C'} {'D', 'E', 'F'}


In [ ]:
# One update step: compute new centroids
C1_points = np.array([points[name] for name in C1])
C2_points = np.array([points[name] for name in C2])

new_mu1 = np.mean(C1_points, axis=0)
new_mu2 = np.mean(C2_points, axis=0)


print(new_mu1)
print(new_mu2)


new_mu1 = [1.5 1.4]
new_mu2 = [5.5        5.66666667]


In [25]:
# Compute objective after update using the same assignments
J_after = 0

for name in C1:
    J_after += squ_euc(points[name], new_mu1)

for name in C2:
    J_after += squ_euc(points[name], new_mu2)

print()
print("J_before =", round(J_before, 4))
print("J_after =", round(J_after, 4))



J_before = 14.91
J_after = 2.7267


In [27]:
# Check whether another iteration changes the assignments
new_C1 = set()
new_C2 = set()

for name, point in points.items():
    d_new_mu1 = squ_euc(point, new_mu1)
    d_new_mu2 = squ_euc(point, new_mu2)
    
    if d_new_mu1 < d_new_mu2:
        new_C1.add(name)
    else:
        new_C2.add(name)


print("new C1", new_C1)
print("new C2", new_C2)


print(C1 != new_C1 or C2 != new_C2)

new C1 {'A', 'B', 'C'}
new C2 {'D', 'E', 'F'}
False
